import { filterPlaces } from "./place-index.mjs";

// Source of truth for the committed place records. The map bundle does not import this module:
// scripts/build-place-data.mjs splits it into public/data/places-index.json and
// public/data/places/<id>.json, which the client loads instead.
export {
  CATEGORIES,
  categoryLabels,
  categorySummary,
  directionsUrlFor,
  isVerified,
  matchesSearch,
  placeCategories,
} from "./place-index.mjs";

const DEMO_ADDRESS = {
  es: "Felipe Carrillo Puerto, Quintana Roo (zona aproximada)",
  en: "Felipe Carrillo Puerto, Quintana Roo (approximate area)",
};

const DEMO_VERIFICATION_NOTE = {
  es: "Punto de ejemplo: ubicación, horario y contacto aún no verificados.",
  en: "Example point: location, hours and contact not yet verified.",
};

const DEMO_LAST_UPDATED = "2026-09-29";

const sanctuary = {
  id: "santuario-de-la-cruz-parlante-fcp",
  category: "culture",
  nameEs: "Santuario de la Cruz Parlante",
  nameEn: "Sanctuary of the Talking Cross",
  shortDescriptionEs: "Santuario maya dedicado a la Cruz Parlante de Chan Santa Cruz, símbolo de la identidad y la resistencia maya durante la Guerra de Castas.",
  shortDescriptionEn: "Maya shrine dedicated to the Talking Cross of Chan Santa Cruz, a symbol of Maya identity and resistance during the Caste War.",
  fullDescriptionEs: "El Santuario de la Cruz Parlante honra a la Cruz Parlante de Chan Santa Cruz —hoy Felipe Carrillo Puerto—, nombre que significa 'Santa Cruz pequeña' o 'querida' en lengua maya. La Cruz surgió como ejemplo del sincretismo entre el catolicismo europeo y la religión tradicional maya: dado que los mayas veneraban árboles como la ceiba, la cruz de madera funcionó como sustituto cristiano y hablaba a los líderes rebeldes en voz de Dios. Los seguidores, llamados Cruzo'ob, formaron en torno a ella uno de los principales pueblos indígenas de México tras la Guerra de Castas. El santuario sigue en pie y puede visitarse; se encuentra junto a un cenote seco, en una pequeña plaza a unas cinco cuadras al oeste de la carretera 307, en la esquina de las calles 60 y 69. La cruz está al lado derecho del altar. No se permite entrar con sombrero ni con calzado. Se celebra misa varias veces al día. Es un sitio de peregrinación al que acude gente de toda la región.",
  fullDescriptionEn: "The Sanctuary of the Talking Cross honors the Talking Cross of Chan Santa Cruz — today's Felipe Carrillo Puerto — a name meaning 'small' or 'dear' Holy Cross in Yucatec Maya. The Cross exemplifies syncretism between European Catholicism and traditional Maya religion: since the Maya venerated trees such as the ceiba, the wooden cross served as a Christian stand-in and spoke to rebel leaders in the voice of God. Its followers, the Cruzo'ob, built around it one of Mexico's main Indigenous towns after the Caste War. The sanctuary still stands and can be visited; it sits next to a dried-up cenote in a small park about five blocks west of Highway 307, at the corner of streets 60 and 69. The cross is on the right side of the altar. Visitors may not enter wearing a hat or shoes. Mass is held several times daily. It is a pilgrimage destination drawing visitors from across the region.",
  latitude: 19.580684047331296,
  longitude: -88.04887785463087,
  coordinateSource: "User-provided coordinates; not independently GPS-verified",
  addressEs: "Calle 60 #788 (esquina con Calle 69), Col. Centro / Cecilio Chi, C.P. 77230, Felipe Carrillo Puerto, Quintana Roo",
  addressEn: "60 Street #788 (corner with 69 Street), Col. Centro / Cecilio Chi, C.P. 77230, Felipe Carrillo Puerto, Quintana Roo",
  community: "Felipe Carrillo Puerto",
  hours: [
    { day: "Mon", open: "07:00", close: "18:00", notesEs: "Misa varias veces al día", notesEn: "Mass held several times daily" },
    { day: "Tue", open: "07:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Wed", open: "07:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Thu", open: "07:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Fri", open: "07:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Sat", open: "07:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Sun", open: "07:00", close: "18:00", notesEs: "", notesEn: "" },
  ],
  phone: null,
  whatsapp: null,
  email: null,
  website: null,
  socialLinks: { facebook: null, instagram: null, tiktok: null },
  directionsUrl: "https://www.waze.com/es-419/live-map/directions/mx/q.r./felipe-carrillo-puerto/santuario-de-la-cruz-parlante?to=place.ChIJ30RtZGB4UI8Rx5xFF1WMlQ0",
  priceLevel: "$",
  paymentMethods: ["cash"],
  languagesSpoken: ["es", "maya"],
  amenities: ["religious_site", "pilgrimage_destination", "park_plaza", "photography_allowed_unverified"],
  accessibility: {
    wheelchairAccess: null,
    parking: null,
    notesEs: "Se requiere entrar sin sombrero ni calzado. Sin información verificada sobre accesibilidad.",
    notesEn: "Visitors must remove hats and shoes before entering. No verified accessibility information.",
  },
  photos: [],
  verified: false,
  verifiedAt: null,
  verifiedBy: null,
  verificationSourceUrls: [
    "https://www.atlasobscura.com/places/santuario-de-la-cruz-parlante-speaking-cross",
    "https://www.lonelyplanet.com/mexico/yucatan-peninsula/felipe-carrillo-puerto/attractions/santuario-de-la-cruz-parlante/a/poi-sig/501630/361691",
    "https://en.wikivoyage.org/wiki/Felipe_Carrillo_Puerto",
    "https://mindtrip.ai/attraction/felipe-carrillo-puerto-quintana-roo/santuario-de-la-cruz-parlante/at-2SEWBHhO",
    "https://www.waze.com/es-419/live-map/directions/mx/q.r./felipe-carrillo-puerto/santuario-de-la-cruz-parlante?to=place.ChIJ30RtZGB4UI8Rx5xFF1WMlQ0",
  ],
  verificationNotes: "Address corroborated by three independent sources (Atlas Obscura, Wikivoyage, Waze/Mindtrip) as Calle 60 #788, corner with Calle 69, CP 77230; coordinates were provided by the user and have not been independently GPS-verified or cross-checked against official INEGI/INAH data. Hours (daily 07:00-18:00) are user-aggregated map data from Mindtrip and Waze, consistent with each other but never confirmed by an official or parish source. Price level '$' is inferred (free entry expected for a place of worship; donations possible) — not documented. Payment methods, languages spoken (Spanish/Maya assumed from context), wheelchair access and parking are all undocumented. Note potential confusion with the nearby Parroquia/Iglesia de la Santa Cruz (Calle 66 con 69 per mass-time directories, Calle 68 per Tripadvisor): Lonely Planet and Wikivoyage indicate the Talking Cross itself now sits in the dedicated sanctuary on Calle 60, while the parish church is a separate building; verify on-site which building tourists should be pointed to. Dress code (no hats/shoes) and 'mass several times daily' come from a Lonely Planet entry whose visit date is unknown. No official phone, email or social media found.",
  lastUpdated: "2026-09-30",
};

const museum = {
  id: "museo-de-la-ciudad-felipe-carrillo-puerto",
  category: "culture",
  nameEs: "Museo de la Ciudad de Felipe Carrillo Puerto",
  nameEn: "Felipe Carrillo Puerto City Museum",
  shortDescriptionEs: "Museo dedicado a la historia y el patrimonio cultural de Felipe Carrillo Puerto, su pasado maya, la Guerra de Castas, el movimiento revolucionario y la vida cotidiana de la región.",
  shortDescriptionEn: "Museum dedicated to the history and cultural heritage of Felipe Carrillo Puerto, its Maya past, the Caste War, the revolutionary movement, and everyday life in the region.",
  fullDescriptionEs: "El Museo de la Ciudad de Felipe Carrillo Puerto documenta la historia local desde la época maya hasta el presente. Se encuentra en la Plaza Cívica (parque central) en Calle 67 #768, Col. Centro, C.P. 77200, prácticamente en el centro geográfico de la ciudad. Exhibe piezas sobre la Guerra de Castas, Chan Santa Cruz, el legado de Felipe Carrillo Puerto como líder revolucionario asesinado en 1924, además de arte y artesanías locales. La ciudad ha sido descrita como un bastión cultural y educativo con galerías de arte y centros culturales. La Casa de la Cultura, también en el parque central, alberga galerías y eventos culturales. Las rutas turísticas del municipio mencionan el museo como parte del circuito cultural del centro. El recinto es pequeño pero con contenido histórico valioso; se recomienda combinar su visita con el Santuario de la Cruz Parlante, el Mercado Benito Juárez y la Parroquia de Santa Cruz.",
  fullDescriptionEn: "The Felipe Carrillo Puerto City Museum documents local history from the Maya period to the present. It is located on the Plaza Cívica (central park) at Calle 67 #768, Col. Centro, C.P. 77200, essentially in the geographic center of town. Exhibits cover the Caste War, Chan Santa Cruz, the legacy of Felipe Carrillo Puerto as a revolutionary leader assassinated in 1924, as well as local art and crafts. The city has been described as a cultural and educational stronghold with art galleries and cultural centers. The Casa de la Cultura, also on the central park, hosts galleries and cultural events. Municipal tourism routes include the museum as part of the downtown cultural circuit. The museum is small but packed with valuable historical content; it is recommended to combine a visit with the Sanctuary of the Talking Cross, the Benito Juárez Market, and the Parish of Santa Cruz.",
  latitude: 19.57802448542231,
  longitude: -88.04537970768848,
  coordinateSource: "User-provided coordinates; not independently GPS-verified",
  addressEs: "Plaza Cívica / Calle 67 #768, Col. Centro, C.P. 77200, Felipe Carrillo Puerto, Quintana Roo",
  addressEn: "Civic Plaza / 67 Street #768, Col. Centro, C.P. 77200, Felipe Carrillo Puerto, Quintana Roo",
  community: "Felipe Carrillo Puerto",
  hours: [
    { day: "Mon", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Tue", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Wed", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Thu", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Fri", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Sat", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Sun", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
  ],
  phone: null,
  whatsapp: null,
  email: null,
  website: null,
  socialLinks: { facebook: null, instagram: null, tiktok: null },
  directionsUrl: "https://www.google.com/maps/search/Museo+de+la+Ciudad+Felipe+Carrillo+Puerto+Quintana+Roo",
  priceLevel: "$",
  paymentMethods: ["cash"],
  languagesSpoken: ["es", "maya"],
  amenities: ["museum", "historical_exhibits", "cultural_events", "local_art"],
  accessibility: {
    wheelchairAccess: null,
    parking: null,
    notesEs: "Sin información verificada sobre accesibilidad.",
    notesEn: "No verified accessibility information.",
  },
  photos: [],
  verified: false,
  verifiedAt: null,
  verifiedBy: null,
  verificationSourceUrls: [
    "https://visitmexico.com/es/destino/18025/felipe-carillo-puerto",
    "https://www.felipecarrillopuerto.gob.mx/carnaval?view=article&amp;id=4&amp;catid=9",
    "https://republica-alterna.com.mx/que-lugares-turisticos-visitar-en-felipe-carrillo-puerto-quintana-roo/",
    "https://www.turismotrenmaya.mx/ciudades/conoce-felipe-carrillo-puerto-quintana-roo/",
    "https://www.komoot.com/es-es/guide/3699063/los-mejores-sitios-que-ver-en-felipe-carrillo-puerto",
    "https://www.felipecarrillopuerto.gob.mx/component/tags/tag/mercado",
  ],
  verificationNotes: "Address (Calle 67 #768, Plaza Cívica, Col. Centro, CP 77200) comes from Visit Mexico's official destination page and is corroborated by the municipal government site. Coordinates were provided by the user and have not been independently GPS-verified. Hours (09:00-18:00 daily) are plausible for a municipal museum but are unverified; no official source lists hours. Price level '$' is inferred from context (small local museum, likely free or low-cost) — not documented. Phone, email, website, social media, and accessibility details are all undocumented. The museum is consistently mentioned across multiple tourism sources as part of the downtown cultural circuit alongside the Casa de la Cultura, Santuario de la Cruz Parlante and the Market. No official phone or social media found. Note: some sources conflate the museum with the Casa de la Cultura or the Parroquia de Santa Cruz (Calle 66 con 69); the municipal government page references the museum separately from the parish church.",
  lastUpdated: "2026-09-30",
};

const casaDeLaCultura = {
  id: "casa-de-la-cultura-felipe-carrillo-puerto",
  category: "culture",
  nameEs: "Casa de la Cultura de Felipe Carrillo Puerto",
  nameEn: "Felipe Carrillo Puerto House of Culture",
  shortDescriptionEs: "Centro cultural en el parque central que alberga galerías de arte, eventos culturales, talleres y la tienda de artesanías \"Kábo'ob Ku Meyajo'ob\" (Manos que Trabajan) de artesanos mayas locales.",
  shortDescriptionEn: "Cultural center on the central park housing art galleries, cultural events, workshops, and the artisan shop 'Kábo'ob Ku Meyajo'ob' (Hands That Work) by local Maya artisans.",
  fullDescriptionEs: "La Casa de la Cultura de Felipe Carrillo Puerto es un centro cultural ubicado en el Parque Principal (Zócalo) de la ciudad, en la Calle 67 #768, Col. Centro, C.P. 77200, prácticamente en el centro geográfico de la ciudad. Alberga galerías de arte, espacios para eventos culturales y talleres educativos. En 2018 se inauguró en sus instalaciones un punto de venta gratuito para artesanías de artesanos mayas del municipio llamado 'Kábo'ob Ku Meyajo'ob' (Manos que Trabajan), donde se exhiben y venden productos textiles y artesanales. El centro forma parte del circuito cultural del municipio junto con el Museo de la Ciudad, el Santuario de la Cruz Parlante y el Mercado Benito Juárez. La ciudad ha sido descrita como un bastión cultural y educativo con galerías de arte y centros culturales.",
  fullDescriptionEn: "The Felipe Carrillo Puerto House of Culture is a cultural center located on the town's main park (Zócalo) at Calle 67 #768, Col. Centro, C.P. 77200, essentially in the geographic center of town. It houses art galleries, spaces for cultural events, and educational workshops. In 2018, a free sales point for crafts by Maya artisans from the municipality was inaugurated under its name, called 'Kábo'ob Ku Meyajo'ob' (Hands That Work), where textile and craft products are exhibited and sold. The center is part of the municipality's cultural circuit alongside the City Museum, the Sanctuary of the Talking Cross, and the Benito Juárez Market. The city has been described as a cultural and educational stronghold with art galleries and cultural centers.",
  latitude: 19.578167300889525,
  longitude: -88.0453221173923,
  coordinateSource: "User-provided coordinates; not independently GPS-verified",
  addressEs: "Calle 67 #768, Parque Principal / Zócalo, Col. Centro, C.P. 77200, Felipe Carrillo Puerto, Quintana Roo",
  addressEn: "67 Street #768, Main Park / Zócalo, Col. Centro, C.P. 77200, Felipe Carrillo Puerto, Quintana Roo",
  community: "Felipe Carrillo Puerto",
  hours: [
    { day: "Mon", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Tue", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Wed", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Thu", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Fri", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Sat", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
    { day: "Sun", open: "09:00", close: "18:00", notesEs: "", notesEn: "" },
  ],
  phone: null,
  whatsapp: null,
  email: null,
  website: null,
  socialLinks: { facebook: null, instagram: null, tiktok: null },
  directionsUrl: "https://www.google.com/maps/search/Casa+de+la+Cultura+Felipe+Carrillo+Puerto+Quintana+Roo",
  priceLevel: null,
  paymentMethods: [],
  languagesSpoken: ["es", "maya"],
  amenities: [
    "cultural_center",
    "art_galleries",
    "workshops",
    "artisan_shop",
    "cultural_events",
    "free_admission",
  ],
  accessibility: {
    wheelchairAccess: null,
    parking: null,
    notesEs: "Sin información verificada sobre accesibilidad.",
    notesEn: "No verified accessibility information.",
  },
  photos: [],
  verified: false,
  verifiedAt: null,
  verifiedBy: null,
  verificationSourceUrls: [
    "https://visitmexico.com/es/destino/18025/felipe-carillo-puerto",
    "https://republica-alterna.com.mx/que-lugares-turisticos-visitar-en-felipe-carrillo-puerto-quintana-roo/",
    "https://sipse.com/novedades/felipe-carrillo-puerto-artistas-artesanos-artesanias-venta-comercializacion-promocion-area-lugar-casa-cultura-compra-comunidades-pesonas-productos-articulos-286426.html",
    "https://www.turismotrenmaya.mx/ciudades/conoce-felipe-carrillo-puerto-quintana-roo/",
  ],
  verificationNotes: "Address (Calle 67 #768, Col. Centro, CP 77200) is corroborated by Visit Mexico and multiple tourism sources. Coordinates were provided by the user and have not been independently GPS-verified. Hours (09:00–18:00 daily) are plausible for a cultural center but are unverified; no official source lists hours. The artisan shop 'Kábo'ob Ku Meyajo'ob' (Manos que Trabajan) was inaugurated in 2018 as a free sales space for Maya artisans; its current operating status is unverified. Price level is null (free cultural space; artisan shop purchases are optional). No phone, email, website, or social media found. The Casa de la Cultura is consistently mentioned alongside the Museo de la Ciudad (same address) and the Parroquia de Santa Cruz — these are separate but adjoining buildings on or near the central park. Some sources conflate the museum, the Casa de la Cultura, and the parish church; they are distinct entities. The Sipse article from 2018 discusses the artisan shop but does not provide current contact details.",
  lastUpdated: "2026-09-30",
};

const plaza = {
  id: "plaza-civica-parque-de-las-palapas-monumento-felipe-carrillo-puerto",
  category: "culture",
  nameEs: "Plaza Cívica / Parque de las Palapas + Monumento a Felipe Carrillo Puerto",
  nameEn: "Civic Plaza / Palapa Park + Monument to Felipe Carrillo Puerto",
  shortDescriptionEs: "Parque central de la ciudad con palapas, monumentos históricos, una fuente y el monumento al gobernador revolucionario Felipe Carrillo Puerto. Punto de encuentro y punto de partida para rutas turísticas.",
  shortDescriptionEn: "Town's central park with palapas, historic monuments, a fountain, and a monument to the revolutionary governor Felipe Carrillo Puerto. A gathering point and starting point for sightseeing routes.",
  fullDescriptionEs: "La Plaza Cívica, conocida localmente como Parque de las Palapas, es el parque principal de Felipe Carrillo Puerto. Se encuentra en el centro de la ciudad, en la intersección de las calles 67 y 68, entre las calles 65 y 69. El parque cuenta con palapas típicas yucatecas, una fuente, bancas, y el Monumento a Felipe Carrillo Puerto — una estatua en bronce del gobernador revolucionario asesinado en 1924. El parque también alberga la Casa de la Cultura, el Museo de la Ciudad y la Parroquia de Santa Cruz en sus alrededores inmediatos. Es un espacio de encuentro comunitario, punto de venta de comida en las palapas y punto de partida para rutas turísticas del municipio. El parque es amplio, con palmeras de coco, caminos empedrados y un ambiente tranquilo. Se encuentra a una cuadra al oeste de la carretera federal 307.",
  fullDescriptionEn: "The Plaza Cívica, locally known as Parque de las Palapas, is Felipe Carrillo Puerto's central park. It is located in the town center at the intersection of streets 67 and 68, between streets 65 and 69. The park features typical Yucatecan palapas, a fountain, benches, and the Monument to Felipe Carrillo Puerto — a bronze statue of the revolutionary governor assassinated in 1924. The park is surrounded by the Casa de la Cultura, the City Museum, and the Parish of Santa Cruz. It serves as a community gathering space, a food-selling area under the palapas, and a starting point for municipal sightseeing routes. The park is spacious, with coconut palms, paved walkways, and a tranquil atmosphere. It sits one block west of the federal highway 307.",
  latitude: 19.578135173994557,
  longitude: -88.0460485056746,
  coordinateSource: "User-provided coordinates; not independently GPS-verified",
  addressEs: "Calle 67 y 68 entre 65 y 69, Col. Centro, C.P. 77200, Felipe Carrillo Puerto, Quintana Roo",
  addressEn: "Streets 67 and 68 between 65th and 69th, Col. Centro, C.P. 77200, Felipe Carrillo Puerto, Quintana Roo",
  community: "Felipe Carrillo Puerto",
  hours: [
    { day: "Mon", open: "", close: "", notesEs: "Espacio público abierto todo el día", notesEn: "Public open space, accessible all day" },
    { day: "Tue", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Wed", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Thu", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Fri", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Sat", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Sun", open: "", close: "", notesEs: "", notesEn: "" },
  ],
  phone: null,
  whatsapp: null,
  email: null,
  website: null,
  socialLinks: { facebook: null, instagram: null, tiktok: null },
  directionsUrl: "https://www.google.com/maps/search/Plaza+Civica+Felipe+Carrillo+Puerto+Quintana+Roo",
  priceLevel: null,
  paymentMethods: [],
  languagesSpoken: ["es"],
  amenities: ["public_park", "monument", "palapas", "food_stalls_nearby", "walking_paths", "cultural_venues_adjoining"],
  accessibility: {
    wheelchairAccess: null,
    parking: null,
    notesEs: "Espacio público con caminos empedrados. Sin información verificada sobre rampas o accesibilidad.",
    notesEn: "Public space with paved walkways. No verified accessibility information.",
  },
  photos: [],
  verified: false,
  verifiedAt: null,
  verifiedBy: null,
  verificationSourceUrls: [
    "https://visitmexico.com/es/destino/18025/felipe-carillo-puerto",
    "https://www.turismotrenmaya.mx/ciudades/conoce-felipe-carrillo-puerto-quintana-roo/",
    "https://republica-alterna.com.mx/que-lugares-turisticos-visitar-en-felipe-carrillo-puerto-quintana-roo/",
    "https://en.wikivoyage.org/wiki/Felipe_Carrillo_Puerto",
  ],
  verificationNotes: "Address corroborated by Wikivoyage as Parque Principal / Calle 67 #768 (one block west of Highway 307) and by multiple sources placing it at Calle 67/68 entre 65 y 69. Coordinates were provided by the user and have not been independently GPS-verified. Hours are left blank because this is a public open-air park (no formal opening hours); the fields note 'espacio público abierto todo el día.' Price level is null (free public space). No phone, email, website, or social media found. The monument to Felipe Carrillo Puerto is consistently referenced across tourism sources. Some sources conflate the park with the Museo de la Ciudad (Calle 67 #768) or the Parroquia de Santa Cruz — these are separate but adjoining buildings. The 'Palapa' designation is confirmed by local tourism pages.",
  lastUpdated: "2026-09-30",
};

const church = {
  id: "iglesia-de-san-servacio-felipe-carrillo-puerto",
  category: "culture",
  nameEs: "Iglesia de San Servacio",
  nameEn: "Church of Saint Servatius",
  shortDescriptionEs: "Iglesia colonial que combina elementos mayas y coloniales en su arquitectura. Situada en el parque central, es un punto de referencia histórico y religioso de la ciudad.",
  shortDescriptionEn: "Colonial church combining Maya and colonial architectural elements. Located on the central park, it is a historic and religious landmark of the town.",
  fullDescriptionEs: "La Iglesia de San Servacio (también mencionada como Parroquia de Santa Cruz en algunas fuentes) es una iglesia colonial que combina elementos mayas y coloniales en su arquitectura. Se encuentra en el parque central de Felipe Carrillo Puerto, en la Calle 66 con 69 No. 782, Col. Centro, C.P. 77200. La iglesia es parte de la Prelatura de Cancún–Chetumal y alberga misas diarias y eventos religiosos. Tiene un campanario, puertas de madera tallada y un altar principal con elementos decorativos. El templo ha sido descrito como modesto pero tranquilo y atractivo en su interior. Algunos visitantes y reseñas la llaman 'Iglesia de la Santa Cruz' o 'Parroquia de Santa Cruz', y una reseña de Tripadvisor menciona que fue la antigua casa de la 'Cruz Parlante' antes de que esta se trasladara al santuario dedicado en Calle 60. La iglesia tiene horarios de misa regulares: misa diaria a las 7:00 AM y 8:00 PM, misa precepto dominical a las 12:00 PM y 8:00 PM, misa con niños a las 8:30 AM del domingo, y bautismos comunitarios los domingos a las 10:00 AM. El horario de oficina es de lunes a viernes de 9:00 AM a 5:00 PM.",
  fullDescriptionEn: "The Church of Saint Servatius (also referred to as the Parish of Santa Cruz in some sources) is a colonial church combining Maya and colonial architectural elements. It is located on the central park of Felipe Carrillo Puerto, at Calle 66 with 69 No. 782, Col. Centro, C.P. 77200. The church is part of the Prelature of Cancún–Chetumal and holds daily masses and religious events. It features a bell tower, carved wooden doors, and a main altar with decorative elements. The temple has been described as modest but tranquil and attractive on the interior. Some visitors and reviews call it the 'Holy Cross Catholic Church' or 'Parish of Santa Cruz,' and a Tripadvisor review notes it was the former home of the Talking Cross before it was relocated to the dedicated sanctuary on Calle 60. The church has regular mass schedules: daily mass at 7:00 AM and 8:00 PM, Sunday precept mass at 12:00 PM and 8:00 PM, Sunday children's mass at 8:30 AM, and community baptisms on Sundays at 10:00 AM. Office hours are Monday to Friday from 9:00 AM to 5:00 PM.",
  latitude: 19.577906662241222,
  longitude: -88.0456236548112,
  coordinateSource: "User-provided coordinates; not independently GPS-verified",
  addressEs: "Calle 66 con 69 No. 782, Col. Centro, C.P. 77200, Felipe Carrillo Puerto, Quintana Roo",
  addressEn: "66 Street with 69 Street No. 782, Col. Centro, C.P. 77200, Felipe Carrillo Puerto, Quintana Roo",
  community: "Felipe Carrillo Puerto",
  hours: [
    { day: "Mon", open: "07:00", close: "20:00", notesEs: "Misa diaria 7:00 AM y 8:00 PM; oficina 9:00 AM - 5:00 PM", notesEn: "Daily mass 7:00 AM and 8:00 PM; office 9:00 AM - 5:00 PM" },
    { day: "Tue", open: "07:00", close: "20:00", notesEs: "", notesEn: "" },
    { day: "Wed", open: "07:00", close: "20:00", notesEs: "", notesEn: "" },
    { day: "Thu", open: "07:00", close: "20:00", notesEs: "", notesEn: "" },
    { day: "Fri", open: "07:00", close: "20:00", notesEs: "", notesEn: "" },
    { day: "Sat", open: "18:00", close: "18:00", notesEs: "Misa 6:00 PM", notesEn: "Mass 6:00 PM" },
    { day: "Sun", open: "08:30", close: "20:00", notesEs: "Misa con niños 8:30 AM; Misa precepto 12:00 PM y 8:00 PM; Bautismos 10:00 AM", notesEn: "Children's mass 8:30 AM; Precept mass 12:00 PM and 8:00 PM; Baptisms 10:00 AM" },
  ],
  phone: null,
  whatsapp: null,
  email: null,
  website: null,
  socialLinks: { facebook: null, instagram: null, tiktok: null },
  directionsUrl: "https://www.google.com/maps/search/Parroquia+Santa+Cruz+Felipe+Carrillo+Puerto+Quintana+Roo",
  priceLevel: null,
  paymentMethods: [],
  languagesSpoken: ["es"],
  amenities: ["church", "mass_services", "baptisms", "cultural_heritage", "colonial_architecture"],
  accessibility: {
    wheelchairAccess: null,
    parking: null,
    notesEs: "Sin información verificada sobre accesibilidad.",
    notesEn: "No verified accessibility information.",
  },
  photos: [],
  // Attributed "verified" by a third-party mass-time directory (naming/coordinates remain uncertain);
  // this does NOT mean the location is physically/GPS verified — see locationAccuracy below.
  verified: true,
  verifiedAt: "2026-09-30",
  verifiedBy: "horariodemisa.com.mx",
  verificationSourceUrls: [
    "https://horariodemisa.com.mx/quintana-roo/felipe-carrillo-puerto/parroquia-santa-cruz-felipe-carrillo-puerto/",
    "https://www.turismotrenmaya.mx/ciudades/conoce-felipe-carrillo-puerto-quintana-roo/",
    "https://www.tripadvisor.com/ShowUserReviews-g2048778-d23335693-r786979314-Holy_Cross_Catholic_Church_iglesia_Santa_Cruz-Felipe_Carrillo_Puerto_Yucatan_P.html",
  ],
  verificationNotes: "Address (Calle 66 con 69 No. 782, Col. Centro, CP 77200) and mass schedules are confirmed by horariodemisa.com.mx, a dedicated mass-time directory. Office hours (Mon–Fri 9:00 AM–5:00 PM) are also listed there. Tripadvisor corroborates the location as a historic church once housing the Talking Cross. Tourism sources describe it as combining Maya and colonial architectural elements. Coordinates were provided by the user and have not been independently GPS-verified. The name varies in sources: 'Iglesia de San Servacio' (tourism pages), 'Parroquia de Santa Cruz' (mass directory), and 'Iglesia de la Santa Cruz' (Tripadvisor). These likely refer to the same building. Phone, email, website, and social media are undocumented. No official diocese page found. Mass schedule is sourced from the mass-time directory — verify before relying on it for planning.",
  lastUpdated: "2026-09-30",
};

const balamNah = {
  id: "balam-nah-felipe-carrillo-puerto",
  // Primary category plus an optional secondary list: a nature spot that also offers lodging.
  // Only the classification was corrected: the sourced descriptions below are kept verbatim
  // because no verified nature or lodging details are available for this record yet.
  category: "nature",
  secondaryCategories: ["lodging"],
  nameEs: "Balam-Nah",
  nameEn: "Balam-Nah",
  shortDescriptionEs: "Centro cultural y museo maya dedicado a preservar la cultura, lengua y tradiciones del pueblo maya en Felipe Carrillo Puerto. Ofrece talleres, exposiciones y eventos culturales.",
  shortDescriptionEn: "Maya cultural center and museum dedicated to preserving the culture, language, and traditions of the Maya people in Felipe Carrillo Puerto. Offers workshops, exhibitions, and cultural events.",
  fullDescriptionEs: "Balam-Nah es un centro cultural y museo maya ubicado en Felipe Carrillo Puerto, Quintana Roo. Su nombre significa 'Casa del Jaguar' en lengua maya (balam = jaguar, nah = casa). El centro se enfoca en la preservación y difusión de la cultura maya, incluyendo su lengua, tradiciones, artesanías y conocimientos ancestrales. Cuenta con espacios para exposiciones, talleres educativos y eventos culturales. El sitio web oficial es balamnah.fcpqroo.mx y está listado en Google Maps. Balam-Nah forma parte del circuito cultural de la ciudad junto con el Museo de la Ciudad, la Casa de la Cultura y el Santuario de la Cruz Parlante. Es un espacio importante para la identidad maya local y el turismo cultural.",
  fullDescriptionEn: "Balam-Nah is a Maya cultural center and museum located in Felipe Carrillo Puerto, Quintana Roo. Its name means 'Jaguar House' in the Maya language (balam = jaguar, nah = house). The center focuses on preserving and promoting Maya culture, including its language, traditions, crafts, and ancestral knowledge. It features spaces for exhibitions, educational workshops, and cultural events. The official website is balamnah.fcpqroo.mx and it is listed on Google Maps. Balam-Nah is part of the city's cultural circuit alongside the City Museum, the Casa de la Cultura, and the Sanctuary of the Talking Cross. It is an important space for local Maya identity and cultural tourism.",
  latitude: 19.476991842956,
  longitude: -88.06736291757169,
  coordinateSource: "User-provided coordinates; not independently GPS-verified",
  addressEs: "",
  addressEn: "",
  community: "Felipe Carrillo Puerto",
  hours: [
    { day: "Mon", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Tue", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Wed", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Thu", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Fri", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Sat", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Sun", open: "", close: "", notesEs: "", notesEn: "" },
  ],
  phone: "",
  whatsapp: "",
  email: "",
  website: "https://balamnah.fcpqroo.mx/",
  socialLinks: { facebook: "", instagram: "", tiktok: "" },
    promotion: {
    cardUrl: "/promo/promotion0_1280_720.webp",
    eventId: "promo-balam-nah",
  },
  directionsUrl: null,
  priceLevel: null,
  paymentMethods: [],
  languagesSpoken: ["es", "maya"],
  amenities: ["museum", "cultural_center", "exhibitions", "workshops", "maya_cultural_preservation"],
  accessibility: { wheelchairAccess: null, parking: null, notesEs: "", notesEn: "" },
  photos: [],
  verified: false,
  verifiedAt: "",
  verifiedBy: "",
  verificationSourceUrls: [
    "https://maps.app.goo.gl/KwaZNGD5pbZUf6bw8",
    "https://balamnah.fcpqroo.mx/",
  ],
  verificationNotes: "Data is limited to the Google Maps listing and the official website (balamnah.fcpqroo.mx). No address, coordinates, hours, phone, or contact information could be extracted from either source — the Google Maps link does not reveal a precise address or coordinates in available snippets, and the website content was not accessible for extraction. The name 'Balam-Nah' means 'Casa del Jaguar' (jaguar house) in Maya. The center is described as focused on Maya cultural preservation, workshops, and exhibitions. It is mentioned in local tourism contexts as part of the cultural circuit. No independent verification of hours, accessibility, pricing, or physical location is available. The website domain (fcpqroo.mx) suggests a municipal or local affiliation but this is unconfirmed. Significant gaps remain: exact address, GPS coordinates, operating hours, contact details, and accessibility information are all unknown. The coordinates were provided by the user and have not been independently GPS-verified.",
  lastUpdated: "2026-09-30",
};

const whippingFountain = {
  id: "pila-de-los-azotes-felipe-carrillo-puerto",
  category: "culture",
  nameEs: "Pila de los Azotes",
  nameEn: "Whipping Fountain (Pila de los Azotes)",
  shortDescriptionEs: "Pila histórica del centro de la ciudad usada para aplicar castigos corporales según los usos y costumbres mayas de Chan Santa Cruz. Uno de los atractivos culturales más singulares de la 'capital de la cultura maya'.",
  shortDescriptionEn: "Historic downtown fountain used to administer corporal punishment under the Maya uses and customs of Chan Santa Cruz. One of the most unusual cultural attractions of the 'capital of Maya culture'.",
  fullDescriptionEs: "La Pila de los Azotes es una pileta de origen histórico ubicada en el centro de Felipe Carrillo Puerto, cerca de la iglesia Balá'an Naj / Parroquia de Santa Cruz. Las fuentes oficiales difieren sobre su fecha de construcción: el gobierno municipal indica que fue construida en 1918 durante el gobierno del general Francisco May Pech, mientras que el portal estatal Zona Maya la atribuye a 1864-1870 bajo el gobernador maya general Crescencio Poot. Lo que sí coinciden todas las fuentes es su función: se usaba para castigar a quienes violaban las leyes de usos y costumbres mayas. La práctica de infringir azotes data desde 1915: el culpable era conducido ante la Cruz, puesto de rodillas con los brazos tendidos, y recibía doce azotes de uno de dos guardias presentes; al terminar rezaba varias oraciones frente a la cruz y quedaba libre de culpa. Con la llegada masiva de trabajadores chicleros de Veracruz, Tabasco y Belice (a quienes los nativos llamaban 'Huaches'), aumentaron los pleitos, y el general May Pech mandó construir la pila para aplicar justicia ejemplar. Según la tradición, por adulterio se aplicaban 50 azotes en público, seguidos de jugo de naranja agria en las heridas y oración frente a la cruz. Hoy es un monumento histórico y punto de interés turístico dentro del circuito del centro histórico.",
  fullDescriptionEn: "The Pila de los Azotes is a historic fountain in downtown Felipe Carrillo Puerto, near the Balá'an Naj church / Parish of Santa Cruz. Official sources disagree on its construction date: the municipal government states it was built in 1918 during the government of General Francisco May Pech, while the state's Zona Maya portal attributes it to 1864-1870 under Maya governor General Crescencio Poot. All sources agree on its function: it was used to punish those who violated Maya laws, uses and customs. The practice of flogging dates from 1915: the offender was led before the Cross, placed on his knees with arms outstretched, and received twelve lashes from one of two guards present; afterwards he prayed several prayers before the cross and was cleared of guilt. With the mass arrival of chicle workers from Veracruz, Tabasco and Belize (whom locals called 'Huaches'), fights increased, and General May Pech ordered the fountain built to apply exemplary justice. According to tradition, adultery was punished with 50 public lashes, followed by sour orange juice rubbed into the wounds and prayer before the cross. Today it is a historic monument and tourist point of interest within the historic-center circuit.",
  // Source record carries latitude/longitude: null; the exported entry below uses a clearly
  // labelled approximate historic-centre point so the record satisfies coordinate validation
  // without implying GPS verification. The point is offset from the church estimate so the
  // marker is not hidden underneath it.
  latitude: 19.577544356982212,
  longitude: -88.0456050409815,
  coordinateSource: "User-provided coordinates; not independently GPS-verified",
  addressEs: "Centro histórico, junto a la Parroquia de Santa Cruz / Balá'an Naj, Col. Centro, C.P. 77200, Felipe Carrillo Puerto, Quintana Roo (dirección exacta no publicada)",
  addressEn: "Historic center, next to the Parish of Santa Cruz / Balá'an Naj, Col. Centro, C.P. 77200, Felipe Carrillo Puerto, Quintana Roo (exact address not published)",
  community: "Felipe Carrillo Puerto",
  hours: [
    { day: "Mon", open: "", close: "", notesEs: "Monumento al aire libre, acceso público", notesEn: "Outdoor monument, public access" },
    { day: "Tue", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Wed", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Thu", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Fri", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Sat", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Sun", open: "", close: "", notesEs: "", notesEn: "" },
  ],
  phone: null,
  whatsapp: null,
  email: null,
  website: "https://felipecarrillopuerto.gob.mx/catastro?id=44&amp;view=category",
  socialLinks: { facebook: null, instagram: null, tiktok: null },
  directionsUrl: "https://www.google.com/maps/search/Pila+de+los+Azotes+Felipe+Carrillo+Puerto",
  priceLevel: null,
  paymentMethods: [],
  languagesSpoken: ["es", "maya"],
  amenities: ["historic_monument", "outdoor_site", "part_of_historic_center_circuit"],
  accessibility: {
    wheelchairAccess: null,
    parking: null,
    notesEs: "Sin información verificada sobre accesibilidad.",
    notesEn: "No verified accessibility information.",
  },
  photos: [],
  verified: false,
  verifiedAt: null,
  verifiedBy: null,
  verificationSourceUrls: [
    "https://quintanaroohoy.com/quintanaroo/fcp/felipe-carrillo-puerto-marcado-por-la-historia/",
    "https://felipecarrillopuerto.gob.mx/catastro?id=44&amp;view=category",
    "http://zonamaya.qroo.gob.mx/centro-historico-de-felipe-carrillo-puerto/",
    "https://paseopormexico.com/lugares/1792/pila_de_los_azotes_en_felipe_carrillo_puerto",
  ],
  verificationNotes: "Existence and historical function confirmed by two official sources: the municipal government tourism page and the state Zona Maya portal. MAJOR DATE CONFLICT between official sources: municipality says built 1918 under General Francisco May Pech; state portal and Paseo por México say built 1864-1870 under General Crescencio Poot. The municipal page itself adds that flogging as a practice dates from 1915 — internally inconsistent with the 1864 attribution but also at odds with its own 1918 date framing. Do not publish a construction date without resolving this. Exact street address and GPS coordinates are NOT published anywhere found; location described only as 'near the Balá'an Naj church' in the historic center. The mapped point was provided by the user, not surveyed or independently GPS-verified, so the entry stays unverified/approximate and no directions link is offered. No hours (open-air public monument), no fees documented. No phone, social media or accessibility info exists for this site.",
  lastUpdated: "2026-09-30",
};

// Historical-memory record: the original tree fell on 23 June 2017 and no current specimen,
// monument or exact point is independently verified. The user-provided coordinates are retained
// as an approximate map point without implying that the original or current site is verified.
const pichTree = {
  id: "arbol-del-pich-felipe-carrillo-puerto",
  category: "nature",
  nameEs: "Árbol del Pich (histórico)",
  nameEn: "The Pich Tree (historic)",
  shortDescriptionEs: "Legendario árbol de unos 200 años, ligado a la historia de Chan Santa Cruz y celebrado con una fiesta tradicional anual. El ejemplar original cayó el 23 de junio de 2017.",
  shortDescriptionEn: "Legendary roughly 200-year-old tree tied to the history of Chan Santa Cruz and honored with a traditional annual festival. The original specimen fell on June 23, 2017.",
  fullDescriptionEs: "El 'Pich' (árbol de chaká / madera de rosa, Haematoxylum campechianum) fue un ejemplar legendario de aproximadamente 200 años de vida, considerado pieza importante de la historia del municipio de Felipe Carrillo Puerto y vinculado a la memoria de la antigua Chan Santa Cruz. Contaba con una fiesta tradicional anual ('la fiesta del árbol'). El árbol cayó el 23 de junio de 2017, un mes antes de la fiesta tradicional, generando fuerte conmoción entre los carrilloportenses: algunos lo interpretaron como mal augurio al inicio de la temporada de huracanes, otros como pérdida patrimonial para las nuevas generaciones, y otros propusieron sembrar un nuevo árbol para iniciar una nueva historia. ESTADO ACTUAL INCIERTO: no se encontró confirmación de si existe un nuevo ejemplar plantado, un monumento en el sitio original, ni la ubicación exacta del árbol original. Verificar en campo antes de publicar esta entrada en un mapa.",
  fullDescriptionEn: "The 'Pich' (logwood tree, Haematoxylum campechianum) was a legendary specimen roughly 200 years old, considered an important piece of the history of the municipality of Felipe Carrillo Puerto and tied to the memory of ancient Chan Santa Cruz. It had a traditional annual celebration ('the tree festival'). The tree fell on June 23, 2017, one month before the traditional festival, causing strong emotion among residents: some read it as an ill omen at the start of hurricane season, others as a heritage loss for new generations, and others proposed planting a new tree to begin a new history. CURRENT STATUS UNCERTAIN: no confirmation was found of a replanted specimen, a monument at the original site, or the exact location of the original tree. Verify on the ground before publishing this entry on a map.",
  latitude: 19.609933175898494,
  longitude: -88.55789465767205,
  coordinateSource: "User-provided coordinates; not independently GPS-verified.",
  addressEs: "Municipio de Felipe Carrillo Puerto, Quintana Roo (ubicación exacta no documentada)",
  addressEn: "Municipality of Felipe Carrillo Puerto, Quintana Roo (exact location not documented)",
  community: "Felipe Carrillo Puerto",
  hours: [
    { day: "Mon", open: null, close: null, notesEs: "Sitio histórico; el árbol original cayó en 2017", notesEn: "Historic site; the original tree fell in 2017" },
    { day: "Tue", open: null, close: null, notesEs: "", notesEn: "" },
    { day: "Wed", open: null, close: null, notesEs: "", notesEn: "" },
    { day: "Thu", open: null, close: null, notesEs: "", notesEn: "" },
    { day: "Fri", open: null, close: null, notesEs: "", notesEn: "" },
    { day: "Sat", open: null, close: null, notesEs: "", notesEn: "" },
    { day: "Sun", open: null, close: null, notesEs: "", notesEn: "" },
  ],
  phone: null,
  whatsapp: null,
  email: null,
  website: null,
  socialLinks: { facebook: null, instagram: null, tiktok: null },
  // No directions: the exact point of the original tree is undocumented.
  directionsUrl: null,
  priceLevel: null,
  paymentMethods: [],
  languagesSpoken: ["es", "maya"],
  amenities: ["historical_memory", "traditional_festival_historical"],
  accessibility: {
    wheelchairAccess: null,
    parking: null,
    notesEs: "Sin información. Sitio no localizado.",
    notesEn: "No information. Site not located.",
  },
  photos: [],
  verified: false,
  verifiedAt: null,
  verifiedBy: null,
  verificationSourceUrls: [],
  verificationNotes: "The original ~200-year-old Pich tree fell on June 23, 2017, one month before its traditional annual festival; this is the only firmly reported fact. CURRENT STATUS UNCERTAIN: no confirmation of a replanted specimen, of a monument at the original site, or of the exact location of the original tree. The source citation supplied with this record (footnote 4) was not accompanied by a URL, so no verification source URL is stored. The coordinates 19.609933175898494, -88.55789465767205 were provided by the user and have not been independently GPS-verified; they remain approximate and no directions are offered. This map marker is a historical-memory point, not confirmation of a currently visitable attraction. Verify on the ground before relying on its location.",
  lastUpdated: "2026-09-30",
};

const nojkaajTour = {
  id: "noj-kaaj-ruta-de-la-resistencia",
  category: "culture",
  secondaryCategories: ["tours"],
  nameEs: "Noj Kaaj — Ruta de la Resistencia",
  nameEn: "Noj Kaaj — Resistance Route",
  shortDescriptionEs: "Caminata histórica de 5 estaciones por el centro de Felipe Carrillo Puerto: comida tradicional maya, arte, música y testimonios, con traductor de inglés. $3,500 MXN por 2 personas.",
  shortDescriptionEn: "Five-station historical walking tour through downtown Felipe Carrillo Puerto: traditional Maya food, art, music and testimonies, with an English translator. $3,500 MXN for 2 people.",
  fullDescriptionEs: "Noj Kaaj («la Gran Ciudad», hoy Felipe Carrillo Puerto) guarda la memoria viva de la resistencia maya en el corazón de la Zona Maya. En este recorrido de 3–4 horas la historia no se cuenta: se camina, se saborea y se escucha, junto a la comunidad que la mantiene viva. Incluye recorrido a pie de cinco estaciones por el centro histórico, preparación y degustación de comida tradicional maya, recorrido de arte (murales y arte maya contemporáneo), historia musical de la resistencia, traductor de inglés, botanas tradicionales y recogida en la estación del Tren Maya. Requiere reservación mínima 3 días antes. Punto de encuentro: Plaza Cívica.",
  fullDescriptionEn: "Noj Kaaj ('the Great Town,' today's Felipe Carrillo Puerto) holds the living memory of the Maya resistance in the heart of the Zona Maya. On this 3–4 hour experience, history isn't told — it's walked, tasted and heard, alongside the community that keeps it alive. Includes a five-station walking route through the historic center, preparation and tasting of traditional Maya food, an art tour (murals and contemporary Maya art), the music history of the resistance, an English translator, traditional appetizers, and pickup at the Tren Maya station. Booking at least 3 days in advance is required. Meeting point: Civic Plaza.",
  latitude: 19.57814,
  longitude: -88.04605,
  coordinateSource: "Approximate meeting point (Plaza Cívica); not GPS-verified",
  addressEs: "Punto de encuentro: Plaza Cívica (Parque de las Palapas), Centro, Felipe Carrillo Puerto, Quintana Roo",
  addressEn: "Meeting point: Civic Plaza (Palapa Park), Centro, Felipe Carrillo Puerto, Quintana Roo",
  community: "Felipe Carrillo Puerto",
  hours: [
    { day: "Mon", open: "", close: "", notesEs: "Solo con reservación (mín. 3 días antes)", notesEn: "By reservation only (min. 3 days ahead)" },
    { day: "Tue", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Wed", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Thu", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Fri", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Sat", open: "", close: "", notesEs: "", notesEn: "" },
    { day: "Sun", open: "", close: "", notesEs: "", notesEn: "" },
  ],
  phone: "",
  whatsapp: "",                       // ← add the real booking number when available
  email: "",
  website: null,
  socialLinks: { facebook: "", instagram: "", tiktok: "" },
  directionsUrl: null,
  priceLevel: "$$$",
  paymentMethods: ["cash"],
  languagesSpoken: ["es", "maya", "en"],
  amenities: [
    "walking_tour", "food_tasting", "art_tour", "music_history",
    "english_translator", "tren_maya_pickup", "advance_booking_required",
  ],
  accessibility: {
    wheelchairAccess: null,
    parking: null,
    notesEs: "Recorrido a pie de 3–4 horas; se recomienda calzado cómodo y protección solar.",
    notesEn: "3–4 hour walking route; comfortable shoes and sun protection recommended.",
  },
  photos: [],
  verified: false,
  verifiedAt: "",
  verifiedBy: "",
  verificationSourceUrls: [],
  verificationNotes: "Listing provided by the tour operator; meeting point pinned approximately at Plaza Cívica and not GPS-verified. Price ($3,500 MXN for 2), schedule and inclusions are per the operator's promotional copy — verify all details with the operator before publishing. Tren Maya times cited (Tulum 10:45 → FCP 12:07; return 18:40) must be confirmed on the official portal as schedules change.",
  lastUpdated: "2026-10-08",
  tourPage: { url: "/tours/noj-kaaj" },
};

export const nonMappablePlaces = [];

// Verified local places should carry exact coordinates and a working directionsUrl.
export const attractions = [
  {
    id: "mercado-felipe-carrillo-puerto",
    category: "food",
    name: {
      es: "Mercado Público Municipal de Felipe Carrillo Puerto",
      en: "Felipe Carrillo Puerto Municipal Public Market",
    },
    description: {
      es: "Mercado municipal con puestos de comida tradicional yucateca, productos locales y artesanías en el centro de la ciudad.",
      en: "Municipal market with traditional Yucatecan food stalls, local products and crafts in the city center.",
    },
    latitude: 19.580894458770345,
    longitude: -88.04402730793707,
    status: "verified",
    locationAccuracy: "exact",
    directionsUrl: "https://maps.app.goo.gl/zJbo8V1rE4ZmYT537",
    address: {
      es: "Calle 66 entre 65 y 67, Col. Centro, Felipe Carrillo Puerto, Quintana Roo",
      en: "66 Street between 65th and 67th, Col. Centro, Felipe Carrillo Puerto, Quintana Roo",
    },
    hours: {
      es: "Lun - Dom: 05:00 - 21:00",
      en: "Mon - Sun: 05:00 - 21:00",
    },
    phone: "800 911 6666",
    whatsapp: null,
    website: null,
    websiteNote: "Under Construction",
    verificationNote: {
      es: "Ubicación verificada físicamente en sitio y confirmada por el equipo; coordenadas tomadas del punto directo en Google Maps.",
      en: "Location physically verified on site and confirmed by the team; coordinates taken from the direct Google Maps pin.",
    },
    lastUpdated: "2026-09-29",
  },
  {
    ...sanctuary,
    name: { es: sanctuary.nameEs, en: sanctuary.nameEn },
    description: { es: sanctuary.shortDescriptionEs, en: sanctuary.shortDescriptionEn },
    address: { es: sanctuary.addressEs, en: sanctuary.addressEn },
    hoursDisplay: { es: "Lun - Dom: 07:00 - 18:00", en: "Mon - Sun: 07:00 - 18:00" },
    status: "unverified",
    locationAccuracy: "approximate",
    verificationNote: sanctuary.verificationNotes,
  },
    {
    ...nojkaajTour,
    name: { es: nojkaajTour.nameEs, en: nojkaajTour.nameEn },
    description: { es: nojkaajTour.shortDescriptionEs, en: nojkaajTour.shortDescriptionEn },
    address: { es: nojkaajTour.addressEs, en: nojkaajTour.addressEn },
    hoursDisplay: {
      es: "Solo con reservación (mín. 3 días antes) · ~3–4 horas",
      en: "By reservation only (min. 3 days ahead) · ~3–4 hours",
    },
    status: "unverified",
    locationAccuracy: "approximate",
    verificationNote: nojkaajTour.verificationNotes,
  },
  {
    ...museum,
    name: { es: museum.nameEs, en: museum.nameEn },
    description: { es: museum.shortDescriptionEs, en: museum.shortDescriptionEn },
    address: { es: museum.addressEs, en: museum.addressEn },
    hoursDisplay: { es: "Lun - Dom: 09:00 - 18:00", en: "Mon - Sun: 09:00 - 18:00" },
    status: "unverified",
    locationAccuracy: "approximate",
    verificationNote: museum.verificationNotes,
  },
  {
    ...casaDeLaCultura,
    name: { es: casaDeLaCultura.nameEs, en: casaDeLaCultura.nameEn },
    description: { es: casaDeLaCultura.shortDescriptionEs, en: casaDeLaCultura.shortDescriptionEn },
    address: { es: casaDeLaCultura.addressEs, en: casaDeLaCultura.addressEn },
    hoursDisplay: { es: "Lun - Dom: 09:00 - 18:00", en: "Mon - Sun: 09:00 - 18:00" },
    status: "unverified",
    locationAccuracy: "approximate",
    verificationNote: casaDeLaCultura.verificationNotes,
  },
  {
    ...plaza,
    name: { es: plaza.nameEs, en: plaza.nameEn },
    description: { es: plaza.shortDescriptionEs, en: plaza.shortDescriptionEn },
    address: { es: plaza.addressEs, en: plaza.addressEn },
    hoursDisplay: { es: "Todos los días: espacio público abierto todo el día", en: "Every day: public open space, accessible all day" },
    status: "unverified",
    locationAccuracy: "approximate",
    verificationNote: plaza.verificationNotes,
  },
  {
    ...church,
    name: { es: church.nameEs, en: church.nameEn },
    description: { es: church.shortDescriptionEs, en: church.shortDescriptionEn },
    address: { es: church.addressEs, en: church.addressEn },
    hoursDisplay: {
      es: "Lun-Vie: 07:00 - 20:00; Sáb: misa 18:00; Dom: 08:30 - 20:00",
      en: "Mon-Fri: 07:00 - 20:00; Sat: mass 18:00; Sun: 08:30 - 20:00",
    },
    // Source's verified:true reflects third-party mass-directory attribution, not GPS/physical
    // verification of coordinates or naming — status/locationAccuracy stay unverified/approximate
    // so isVerified()/directionsUrlFor() never claim exact verification for this record.
    status: "unverified",
    locationAccuracy: "approximate",
    verificationNote: church.verificationNotes,
  },
  {
    ...balamNah,
    name: { es: balamNah.nameEs, en: balamNah.nameEn },
    description: { es: balamNah.shortDescriptionEs, en: balamNah.shortDescriptionEn },
    address: { es: balamNah.addressEs, en: balamNah.addressEn },
    hoursDisplay: { es: "", en: "" },
    status: "unverified",
    locationAccuracy: "approximate",
    verificationNote: balamNah.verificationNotes,
  },
  {
    ...whippingFountain,
    name: { es: whippingFountain.nameEs, en: whippingFountain.nameEn },
    description: { es: whippingFountain.shortDescriptionEs, en: whippingFountain.shortDescriptionEn },
    address: { es: whippingFountain.addressEs, en: whippingFountain.addressEn },
    hoursDisplay: {
      es: "Todos los días: monumento al aire libre, acceso público",
      en: "Every day: outdoor monument, public access",
    },
    status: "unverified",
    locationAccuracy: "approximate",
    verificationNote: whippingFountain.verificationNotes,
  },
  {
    ...pichTree,
    name: { es: pichTree.nameEs, en: pichTree.nameEn },
    description: { es: pichTree.shortDescriptionEs, en: pichTree.shortDescriptionEn },
    address: { es: pichTree.addressEs, en: pichTree.addressEn },
    hoursDisplay: {
      es: "Sitio histórico; el árbol original cayó el 23 de junio de 2017",
      en: "Historic site; the original tree fell on June 23, 2017",
    },
    status: "unverified",
    locationAccuracy: "approximate",
    mappable: true,
    verificationNote: pichTree.verificationNotes,
  },
  {
  id: "estacion-tren-maya-felipe-carrillo-puerto",
  category: "tours",
  secondaryCategories: ["culture"],
  name: {
    es: "Estación Tren Maya Felipe Carrillo Puerto",
    en: "Felipe Carrillo Puerto Tren Maya Station",
  },
  description: {
    es: "Estación del Tren Maya (Tramo 6, Tulum–Chetumal) con base de mantenimiento y servicios de turismo Maya Ka'an. Punto de llegada recomendado: Tulum ~1 h, Bacalar ~45 min, Chetumal ~1 h. Compra boletos y consulta horarios en la app oficial del Tren Maya.",
    en: "Tren Maya station (Tramo 6, Tulum–Chetumal) with a maintenance base and Maya Ka'an tourism services. Recommended arrival point: Tulum ~1 h, Bacalar ~45 min, Chetumal ~1 h. Buy tickets and check schedules in the official Tren Maya app.",
  },
  latitude: 19.5837,
  longitude: -88.055,
  status: "unverified",
  locationAccuracy: "approximate",
  directionsUrl: null,
  address: {
    es: "Zona de la estación del Tren Maya, Felipe Carrillo Puerto, Quintana Roo (ubicación exacta por confirmar)",
    en: "Tren Maya station area, Felipe Carrillo Puerto, Quintana Roo (exact location to be confirmed)",
  },
  hoursDisplay: {
    es: "Según horarios de circulación del Tren Maya (consultar app oficial)",
    en: "Per Tren Maya circulation schedules (check official app)",
  },
  phone: null,
  whatsapp: null,
  website: "https://trenmaya.gob.mx/",
  verificationNote: {
    es: "La estación existe y presta servicio en el Tramo 6 según el sitio oficial del Tren Maya; las coordenadas son un punto aproximado del área de la estación y deben confirmarse con GPS en campo antes de ofrecer indicaciones.",
    en: "The station exists and serves Tramo 6 per the official Tren Maya site; coordinates are an approximate point in the station area and must be GPS-confirmed in the field before offering directions.",
  },
  lastUpdated: "2026-10-03",
},
{
  id: "terminal-ado-felipe-carrillo-puerto",
  category: "tours",
  name: {
    es: "Terminal ADO Felipe Carrillo Puerto",
    en: "Felipe Carrillo Puerto ADO Terminal",
  },
  description: {
    es: "Terminal de autobuses ADO en el centro: conexiones frecuentes con Tulum (~1 h), Playa del Carmen (~2 h), Cancún (~3.5–4 h) y Chetumal/Bacalar (~1.5–2 h). Junto a las salidas de colectivos hacia Tulum y comunidades de la Zona Maya. Boletos en la app ADO o en taquilla.",
    en: "Downtown ADO bus terminal: frequent services to Tulum (~1 h), Playa del Carmen (~2 h), Cancún (~3.5–4 h) and Chetumal/Bacalar (~1.5–2 h). Colectivo stands to Tulum and Zona Maya communities are adjacent. Tickets via the ADO app or at the counter.",
  },
  latitude: 19.5776,
  longitude: -88.0448,
  status: "unverified",
  locationAccuracy: "approximate",
  directionsUrl: null,
  address: {
    es: "Centro, Felipe Carrillo Puerto, Quintana Roo (dirección exacta por confirmar)",
    en: "Downtown, Felipe Carrillo Puerto, Quintana Roo (exact address to be confirmed)",
  },
  hoursDisplay: {
    es: "Taquillas según horarios de salida (app ADO)",
    en: "Ticket counter per departure schedules (ADO app)",
  },
  phone: null,
  whatsapp: null,
  website: "https://www.ado.com.mx/",
  verificationNote: {
    es: "La terminal ADO opera en el centro de FCP según la red nacional ADO; las coordenadas son aproximadas y deben verificarse en campo. Horarios y tarifas varían — confirmar siempre en la app ADO.",
    en: "The ADO terminal operates in downtown FCP per the national ADO network; coordinates are approximate and must be field-verified. Schedules and fares vary — always confirm in the ADO app.",
  },
  lastUpdated: "2026-10-03",
},
{
  id: "zona-arqueologica-muyil-chunyaxche",
  category: "culture",
  secondaryCategories: ["nature"],
  name: {
    es: "Zona Arqueológica de Muyil (Chunyaxché)",
    en: "Muyil Archaeological Site (Chunyaxché)",
  },
  description: {
    es: "Sitio maya compacto envuelto en selva a orillas de la laguna Muyil, con la pirámide El Castillo como pieza principal. A ~30 min de FCP hacia Tulum; se combina con el paseo en lancha y el flotador por el canal Maya en la laguna. Cobro de acceso INAH; confirmar tarifa vigente.",
    en: "Compact Maya site wrapped in jungle on the shore of Muyil lagoon, with the El Castillo pyramid as its centerpiece. ~30 min from FCP toward Tulum; combine with the boat ride and canal float on the lagoon. INAH entrance fee applies; confirm current rate.",
  },
  latitude: 19.7586,
  longitude: -87.7067,
  status: "unverified",
  locationAccuracy: "approximate",
  directionsUrl: null,
  address: {
    es: "Muyil, a un lado de la carretera 307, Municipio de Felipe Carrillo Puerto, Quintana Roo",
    en: "Muyil, off Highway 307, Municipality of Felipe Carrillo Puerto, Quintana Roo",
  },
  hoursDisplay: {
    es: "Lun - Dom: aprox. 08:00 - 17:00 (confirmar con INAH)",
    en: "Mon - Sun: approx. 08:00 - 17:00 (confirm with INAH)",
  },
  phone: null,
  whatsapp: null,
  website: "https://www.inah.gob.mx/",
  verificationNote: {
    es: "Sitio publicado por INAH como Zona Arqueológica Muyil; las coordenadas corresponden al área del sitio publicada en mapas pero no se verificaron con GPS. Horarios y tarifas oficiales deben confirmarse en inah.gob.mx.",
    en: "Site published by INAH as Muyil Archaeological Zone; coordinates match the published site area on maps but were not GPS-verified. Official hours and fees must be confirmed at inah.gob.mx.",
  },
  lastUpdated: "2026-10-03",
},
{
  id: "laguna-muyil-flotador-sian-kaan",
  category: "nature",
  secondaryCategories: ["tours"],
  name: {
    es: "Laguna Muyil — Flotador del Canal Maya (Sian Ka'an)",
    en: "Muyil Lagoon — Maya Canal Float (Sian Ka'an)",
  },
  description: {
    es: "El famoso 'río lento' de Sian Ka'an: camino de maderas a través de la selva, lancha comunitaria cruzando la laguna y flotación con chaleco por un canal maya de ~500 m entre manglares. Operado por guías de la comunidad de Muyil (2–3 h en total). Llevar efectivo, repelente biodegradable y calzado acuático; salidas tempranas para aves y agua calmada.",
    en: "The famous Sian Ka'an 'lazy river': boardwalk through the forest, a community boat across the lagoon, and a life-vest float down a ~500 m ancient Maya canal through mangroves. Run by Muyil community guides (2–3 h total). Bring cash, biodegradable repellent and water shoes; early departures for birds and calm water.",
  },
  latitude: 19.771,
  longitude: -87.724,
  status: "unverified",
  locationAccuracy: "approximate",
  directionsUrl: null,
  address: {
    es: "Acceso comunitario Muyil, carretera 307, Quintana Roo (ubicación exacta por confirmar)",
    en: "Muyil community entrance, Highway 307, Quintana Roo (exact location to be confirmed)",
  },
  hoursDisplay: {
    es: "Salidas diarias por la mañana; reservar con anticipación en temporada alta",
    en: "Daily morning departures; book ahead in high season",
  },
  phone: null,
  whatsapp: null,
  website: null,
  verificationNote: {
    es: "La experiencia está documentada por fuentes turísticas regionales y la comunidad de Muyil como operador; las coordenadas son aproximadas (área del embarcadero) y los precios comunitarios cambian — confirmar con los guías locales.",
    en: "The experience is documented by regional tourism sources with Muyil community as operator; coordinates are approximate (boat-launch area) and community fees change — confirm with local guides.",
  },
  lastUpdated: "2026-10-03",
},
{
  id: "reserva-much-kanan-kaax-siijil-noh-ha",
  category: "nature",
  secondaryCategories: ["lodging", "tours"],
  name: {
    es: "Reserva Comunitaria Much Kanan K'áax / Ecocabañas Síijil Noh Ha",
    en: "Much Kanan K'áax Community Reserve / Síijil Noh Ha Ecolodges",
  },
  description: {
    es: "Reserva comunitaria de ~1,230 hectáreas administrada por familias mayas, a unos 10 km de FCP (comunidad de Tres Reyes). Cabañas rústicas con alimentos incluidos, kayak en la laguna, ciclismo de montaña, baños de temazcal y comida yucateca casera. Reservar con anticipación por WhatsApp; se agradece algo de español.",
    en: "~1,230-hectare community reserve run by Maya families, ~10 km from FCP (Tres Reyes community). Rustic cabins with meals included, lagoon kayaking, mountain biking, temazcal baths and home-cooked Yucatecan food. Book ahead via WhatsApp; a little Spanish goes a long way.",
  },
  latitude: 19.5108,
  longitude: -88.0803,
  status: "unverified",
  locationAccuracy: "approximate",
  directionsUrl: null,
  address: {
    es: "Comunidad de Tres Reyes, Felipe Carrillo Puerto, Quintana Roo (ubicación aproximada)",
    en: "Tres Reyes community, Felipe Carrillo Puerto, Quintana Roo (approximate location)",
  },
  hoursDisplay: {
    es: "Reservaciones previas (WhatsApp); kayak y actividades según disponibilidad",
    en: "Advance reservations (WhatsApp); kayaking and activities per availability",
  },
  phone: null,
  whatsapp: null,
  website: null,
  verificationNote: {
    es: "Reserva documentada en el circuito de turismo comunitario Maya Ka'an como 'Kayak en la laguna Siijil Noh Ha'; las coordenadas son un punto aproximado en el área de Tres Reyes y requieren verificación GPS. Agregar teléfono/WhatsApp local cuando se confirme en campo.",
    en: "Reserve documented in the Maya Ka'an community tourism circuit as 'Kayak en la laguna Siijil Noh Ha'; coordinates are an approximate point in the Tres Reyes area and require GPS verification. Add local phone/WhatsApp once confirmed in the field.",
  },
  lastUpdated: "2026-10-03",
},
{
  id: "museo-de-la-guerra-de-castas-tihosuco",
  category: "culture",
  name: {
    es: "Museo de la Guerra de Castas (Tihosuco)",
    en: "Museum of the Caste War (Tihosuco)",
  },
  description: {
    es: "Tihosuco, a ~1 h de FCP, fue uno de los epicentros de la Guerra de Castas. Su museo documenta el conflicto con salas dedicadas a la historia maya yucateca, la sociedad colonial, la guerra y la religión. El templo y exconvento colonial con mural de la época y los talleres de artesanía local completan la visita.",
    en: "Tihosuco, ~1 h from FCP, was one of the epicenters of the Caste War. Its museum documents the conflict with halls devoted to Yucatec Maya history, colonial society, the war and religion. The colonial church with a period mural and local artisan workshops round out the visit.",
  },
  latitude: 19.8628,
  longitude: -88.3717,
  status: "unverified",
  locationAccuracy: "approximate",
  directionsUrl: null,
  address: {
    es: "Tihosuco, Municipio de Felipe Carrillo Puerto, Quintana Roo",
    en: "Tihosuco, Municipality of Felipe Carrillo Puerto, Quintana Roo",
  },
  hoursDisplay: {
    es: "Martes - Domingo aprox. 09:00 - 17:00 (confirmar horario actual)",
    en: "Tue - Sun approx. 09:00 - 17:00 (confirm current hours)",
  },
  phone: null,
  whatsapp: null,
  website: null,
  verificationNote: {
    es: "Museo publicado por el programa Maya Ka'an y fuentes estatales de turismo como parte del circuito de Tihosuco; coordenadas aproximadas del centro de Tihosuco — verificar el punto exacto y el horario en campo.",
    en: "Museum published by the Maya Ka'an program and state tourism sources as part of the Tihosuco circuit; approximate coordinates of Tihosuco center — verify exact point and hours in the field.",
  },
  lastUpdated: "2026-10-03",
},
{
  id: "kantemo-cueva-de-las-serpientes-colgantes",
  category: "nature",
  secondaryCategories: ["tours"],
  name: {
    es: "Cueva de las Serpientes Colgantes (Kantemó)",
    en: "Cave of the Hanging Snakes (Kantemó)",
  },
  description: {
    es: "Al atardecer cientos de murciélagos salen de la cueva mientras culebras colgadas del techo los cazan en pleno vuelo — uno de los espectáculos naturales más singulares de la península. Visitas comunitarias con guía local; carretera de terracería — se recomienda tour comunitario o vehículo de alta clearance. Llevar linterna y efectivo.",
    en: "At dusk hundreds of bats leave the cave while snakes hanging from the ceiling snatch them mid-flight — one of the most singular natural spectacles on the peninsula. Community visits with local guide; dirt road — a community tour or high-clearance vehicle is recommended. Bring a flashlight and cash.",
  },
  latitude: 19.9167,
  longitude: -88.8667,
  status: "unverified",
  locationAccuracy: "approximate",
  directionsUrl: null,
  address: {
    es: "Kantemó, Municipio de Felipe Carrillo Puerto, Quintana Roo (acceso por camino de terracería)",
    en: "Kantemó, Municipality of Felipe Carrillo Puerto, Quintana Roo (access via dirt road)",
  },
  hoursDisplay: {
    es: "Visitas al atardecer, con reservación por guía comunitario",
    en: "Sunset visits, by reservation with a community guide",
  },
  phone: null,
  whatsapp: null,
  website: null,
  verificationNote: {
    es: "Atracción documentada por el programa Maya Ka'an como tour comunitario de Kantemó; las coordenadas son aproximadas (área de la comunidad) y el punto exacto de la cueva debe confirmarse con el guía local. No publicar indicaciones hasta verificar acceso y coordenadas.",
    en: "Attraction documented by the Maya Ka'an program as a Kantemó community tour; coordinates are approximate (community area) and the exact cave point must be confirmed with the local guide. Do not publish directions until access and coordinates are verified.",
  },
  lastUpdated: "2026-10-03",
},
{
  id: "chunhuhub-secretos-de-la-cocina-maya",
  category: "tours",
  secondaryCategories: ["food", "culture"],
  name: {
    es: "Chunhuhub — Secretos de la Cocina Maya (tour comunitario)",
    en: "Chunhuhub — Secrets of Maya Cooking (community tour)",
  },
  description: {
    es: "En la comunidad de Chunhuhub (~50 km al oeste de FCP), mujeres mayas locales comparten la cocina tradicional: el maíz, el pib (horno de tierra) y la elaboración de la tortilla a mano, en un recorrido por ranchos familiares con comida incluida. Reservar con anticipación; ingresos para la comunidad.",
    en: "In the community of Chunhuhub (~50 km west of FCP), local Maya women share traditional cooking: corn, the pib (earth oven) and hand-made tortillas, on a tour of family homesteads with food included. Book ahead; revenue supports the community.",
  },
  latitude: 19.6139,
  longitude: -88.5997,
  status: "unverified",
  locationAccuracy: "approximate",
  directionsUrl: null,
  address: {
    es: "Chunhuhub, Municipio de Felipe Carrillo Puerto, Quintana Roo",
    en: "Chunhuhub, Municipality of Felipe Carrillo Puerto, Quintana Roo",
  },
  hoursDisplay: {
    es: "Con reservación previa (WhatsApp)",
    en: "By advance reservation (WhatsApp)",
  },
  phone: null,
  whatsapp: null,
  website: null,
  verificationNote: {
    es: "Tour publicado por el programa Maya Ka'an como 'Secretos de la cocina Maya' en Chunhuhub; coordenadas aproximadas del centro de la comunidad. Falta contacto local — obtener teléfono/WhatsApp del operador comunitario en campo.",
    en: "Tour published by the Maya Ka'an program as 'Secretos de la cocina Maya' in Chunhuhub; approximate community-center coordinates. Local contact missing — obtain the community operator's phone/WhatsApp in the field.",
  },
  lastUpdated: "2026-10-03",
},
];

export function filterAttractions(category, query = "") {
  return filterPlaces(attractions, category, query);
}
