// Loads the static place payloads generated by scripts/build-place-data.mjs: the marker index
// on first paint, and one detail file per place when that place is selected. Details are cached
// in memory so revisiting a place does not refetch it.

const PLACE_INDEX_URL = "/data/places-index.json";

const detailCache = new Map();

export function placeDetailUrl(id) {
  return `/data/places/${encodeURIComponent(id)}.json`;
}

export async function loadPlaceIndex(signal) {
  const response = await fetch(PLACE_INDEX_URL, { signal });
  if (!response.ok) throw new Error(`Place index request failed: ${response.status}`);
  return response.json();
}

async function fetchPlaceDetail(id, signal) {
  const url = placeDetailUrl(id);
  const timeoutSignal = typeof AbortSignal?.timeout === "function" ? AbortSignal.timeout(5000) : null;
  const combinedSignal =
    signal && timeoutSignal && typeof AbortSignal?.any === "function"
      ? AbortSignal.any([signal, timeoutSignal])
      : signal || timeoutSignal;

  try {
    const options = combinedSignal ? { signal: combinedSignal } : {};
    const response = await fetch(url, options);
    if (!response.ok) {
      const err = new Error(`Place detail request failed: ${response.status}`);
      err.status = response.status;
      throw err;
    }
    return await response.json();
  } catch (cause) {
    if (typeof caches !== "undefined") {
      try {
        if (typeof caches.open === "function") {
          const cache = await caches.open("fcp-places-v1");
          const cached = await cache.match(url);
          if (cached) return await cached.json();
        }
        if (typeof caches.match === "function") {
          const cached = await caches.match(url);
          if (cached) return await cached.json();
        }
      } catch {
        // ignore cache lookup error
      }
    }
    throw cause;
  }
}

function abortError() {
  const error = new Error("The place detail request was cancelled");
  error.name = "AbortError";
  return error;
}

// Rejects as soon as the caller stops caring about the result, without disturbing the shared
// request: another selection of the same place still resolves from it.
function untilAborted(pending, signal) {
  if (signal.aborted) return Promise.reject(abortError());
  return new Promise((resolve, reject) => {
    const cancel = () => reject(abortError());
    signal.addEventListener("abort", cancel, { once: true });
    pending.then(resolve, reject).finally(() => signal.removeEventListener("abort", cancel));
  });
}

// One request per place: the in-flight promise is cached, so reselecting a place while its
// detail is loading never starts a second request. A failed request drops out of the cache so
// the next selection can retry it.
export function loadPlaceDetail(id, signal) {
  let pending = detailCache.get(id);
  if (!pending) {
    pending = fetchPlaceDetail(id).catch((cause) => {
      if (detailCache.get(id) === pending) detailCache.delete(id);
      throw cause;
    });
    detailCache.set(id, pending);
  }
  return signal ? untilAborted(pending, signal) : pending;
}

export function clearPlaceDetailCache() {
  detailCache.clear();
}
