// Loads the static place payloads generated by scripts/build-place-data.mjs: the marker index
// on first paint, and one detail file per place when that place is selected. Details are cached
// in memory so revisiting a place does not refetch it.

const PLACE_INDEX_URL = "/data/places-index.json";

const detailCache = new Map();

export function placeDetailUrl(id) {
  return `/data/places/${encodeURIComponent(id)}.json`;
}

export async function loadPlaceIndex(signal) {
  const response = await fetch(PLACE_INDEX_URL, { signal });
  if (!response.ok) throw new Error(`Place index request failed: ${response.status}`);
  return response.json();
}

export async function loadPlaceDetail(id, signal) {
  const cached = detailCache.get(id);
  if (cached) return cached;

  const response = await fetch(placeDetailUrl(id), { signal });
  if (!response.ok) throw new Error(`Place detail request failed: ${response.status}`);
  const detail = await response.json();
  // A cancelled selection must not poison the cache with a partial or unused response.
  if (!signal?.aborted) detailCache.set(id, detail);
  return detail;
}

export function clearPlaceDetailCache() {
  detailCache.clear();
}
