// Loads the static place payloads generated by scripts/build-place-data.mjs: the marker index
// on first paint, and one detail file per place when that place is selected. Details are cached
// in memory so revisiting a place does not refetch it.

const PLACE_INDEX_URL = "/data/places-index.json";

const detailCache = new Map();

export function placeDetailUrl(id) {
  return `/data/places/${encodeURIComponent(id)}.json`;
}

export async function loadPlaceIndex(signal) {
  const response = await fetch(PLACE_INDEX_URL, { signal });
  if (!response.ok) throw new Error(`Place index request failed: ${response.status}`);
  return response.json();
}

async function fetchPlaceDetail(id) {
  const response = await fetch(placeDetailUrl(id));
  if (!response.ok) throw new Error(`Place detail request failed: ${response.status}`);
  return response.json();
}

function abortError() {
  const error = new Error("The place detail request was cancelled");
  error.name = "AbortError";
  return error;
}

// Rejects as soon as the caller stops caring about the result, without disturbing the shared
// request: another selection of the same place still resolves from it.
function untilAborted(pending, signal) {
  if (signal.aborted) return Promise.reject(abortError());
  return new Promise((resolve, reject) => {
    const cancel = () => reject(abortError());
    signal.addEventListener("abort", cancel, { once: true });
    pending.then(resolve, reject).finally(() => signal.removeEventListener("abort", cancel));
  });
}

// One request per place: the in-flight promise is cached, so reselecting a place while its
// detail is loading never starts a second request. A failed request drops out of the cache so
// the next selection can retry it.
export function loadPlaceDetail(id, signal) {
  let pending = detailCache.get(id);
  if (!pending) {
    pending = fetchPlaceDetail(id).catch((cause) => {
      if (detailCache.get(id) === pending) detailCache.delete(id);
      throw cause;
    });
    detailCache.set(id, pending);
  }
  return signal ? untilAborted(pending, signal) : pending;
}

export function clearPlaceDetailCache() {
  detailCache.clear();
}
